/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalStaffWorkAreaJPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Essentials.Product;
import Business.Essentials.ProductCatalog;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Organization.AdminOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.InsuranceAdminWorkArea.ViewPolicyWorkAreaJPanel;

/**
 *
 * @author Anjali
 */
public class HospitalStaffWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalStaffWorkAreaJPanel
     */
    private JPanel userProcessContainer;
 private ProductCatalog productcatalog;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem ecosystem;
    public HospitalStaffWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,  Enterprise enterprise,EcoSystem ecosystem) {
        initComponents();
  
        this.ecosystem=ecosystem;
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        
        
        
        
        //txtName.setText(s.getSupplyName());
        populateEssentialTable();
    }
public void populateEssentialTable(){
        DefaultTableModel model = (DefaultTableModel)essentialTable.getModel();
        model.setRowCount(0);
        List<Product> productList = ecosystem.getProductCatalog().getProductcatalog(); 
        
        for(Product tester: productList){
            
            
            
            if(tester.getEnterpriseName().equals(enterprise.getName())){
            if(tester.getProdName().equalsIgnoreCase("General Room") || tester.getProdName().equalsIgnoreCase("gr")){
                int countR=tester.getAvail();
                txtRoomCount.setText(String.valueOf(countR));
            }else if(tester.getProdName().equalsIgnoreCase("Deluxe Room")|| tester.getProdName().equalsIgnoreCase("dr") ){
                int countR=tester.getAvail();
                txtDeluxe.setText(String.valueOf(countR));
            }else
            if(tester.getProdName().equalsIgnoreCase("ICU") ){
                int countR=tester.getAvail();
                txtICU.setText(String.valueOf(countR));
            }
            else{
            
            Object row[] = new Object[4];
                 row[0] = tester;
                 row[1] = tester.getAvail();
                      
                 
            model.addRow(row);    
            }
        }
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRoomCount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtICU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDeluxe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        essentialTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Hospital Staff- Essentials Management");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/staff.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 102));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/addProduct.png"))); // NOI18N
        btnCreate.setText("Add");
        btnCreate.setContentAreaFilled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 160, 70));

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 102, 102));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/viewProduct.png"))); // NOI18N
        btnView.setText("View");
        btnView.setContentAreaFilled(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 190, 70));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 102, 102));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/deleteProduct.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("General Room");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, 20));

        txtRoomCount.setText(" ");
        txtRoomCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomCountActionPerformed(evt);
            }
        });
        jPanel2.add(txtRoomCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Room Avaliability Count");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 210, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("ICU ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, 20));

        txtICU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICUActionPerformed(evt);
            }
        });
        jPanel2.add(txtICU, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 140, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Deluxe Room");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, 20));
        jPanel2.add(txtDeluxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 140, 20));

        essentialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        essentialTable.setAutoscrolls(false);
        essentialTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        essentialTable.setGridColor(new java.awt.Color(0, 51, 51));
        essentialTable.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setViewportView(essentialTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 390, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/hospital_room.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        CreateJPanel panel=new CreateJPanel(userProcessContainer,ecosystem,enterprise);
        userProcessContainer.add("CreateJPanel",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRow =  essentialTable.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

        }

        else
        { 
            Product p = (Product) essentialTable.getValueAt(selectedRow, 0);
            System.out.println(p);
            ViewJPanel vpeaj = new ViewJPanel(userProcessContainer, ecosystem, p);
            userProcessContainer.add("ViewJPanel", vpeaj);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtRoomCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomCountActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtRoomCountActionPerformed

    private void txtICUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICUActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = essentialTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the car details", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION);
            {
//                Car car = (Car) tblCarDetails.getValueAt(selectedRow, 0);
//                carDirectory.deleteCar(car);
//                populateTable();
                
                Product p=(Product)essentialTable.getValueAt(selectedRow,0);
                ecosystem.getProductCatalog().removeProduct(p);
                
                populateEssentialTable();
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTable essentialTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDeluxe;
    private javax.swing.JTextField txtICU;
    private javax.swing.JTextField txtRoomCount;
    // End of variables declaration//GEN-END:variables
}
