/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Network.Network;
import Business.Patient.Patient;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Position;

/**
 *
 * @author Anjali
 */
public class ViewPolicyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPolicyWorkAreaJPanel
     */
    InsurancePolicy i;
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    boolean b;
    public ViewPolicyWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem, InsurancePolicy i,boolean b) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.i = i;
        this.b=b;

        txtPolicyMax.setEnabled(false);
        txtPolicyName.setEnabled(false);
        txtMonthly.setEnabled(false);
        txtMin.setEnabled(false);
        txtPrimaryCare.setEnabled(false);
        txtAnnualOut.setEnabled(false);
        txtSpecialistCare.setEnabled(false);
        txtEmergencyRoomCare.setEnabled(false);
        txtSurgery.setEnabled(false);
        txtLabServices.setEnabled(false);
        txtInpatients.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtMin.setEnabled(false);
        txtPolicyType.setEnabled(false);
        jComboBoxAgeGroup.setEnabled(false);
        
        txtDeductible2.setEnabled(false);
        btnAddHospital.setEnabled(false);
        btnAddLaboratory.setEnabled(false);
        btnAddPharmacy.setEnabled(false);
        
        if (b==false){
            saveBtn.setEnabled(false);
        UpdateBtn.setEnabled(false);
        }else{
        saveBtn.setEnabled(false);
        UpdateBtn.setEnabled(true);
        }
        
        
        txtPolicyMax.setText(i.getPolicyMax());
        txtPolicyName.setText(i.getPolicyName());
        txtMonthly.setText(String.valueOf(i.getMonthlyPremium()));
        txtDeductible2.setText(String.valueOf(i.getDeductable()));
        txtPrimaryCare.setText(String.valueOf(i.getPrimaryCare()));
        txtAnnualOut.setText(i.getOutOfPocket());
        txtSpecialistCare.setText(String.valueOf(i.getSpecialist()));
        txtEmergencyRoomCare.setText(String.valueOf(i.getEmergency()));
        txtSurgery.setText(String.valueOf(i.getEmergency()));
        txtLabServices.setText(String.valueOf(i.getEmergency()));
        txtInpatients.setText(String.valueOf(i.getEmergency()));
        txtZipCode.setText(i.getZipCode());
        txtMin.setText(i.getAgeGroup());
        txtPolicyType.setText(i.getPolicyType());
        
        
        
        
        
        
        
        for(Network network:ecosystem.getNetworkList()){
    for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
    if(e.getEnterpriseType().getValue().equals("Hospital")){
           jComboHospital.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Pharmacy"))
            {jComboPharmacy.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Laboratory"))
            {jComboLaboratories.addItem(e.getName());   
        
    }
                
            }
        }
        
        
        
        populateTable();
       
        populatePatients();
        populatePharmacy();
        populateLaboratory();
        populateHospitals();
        
    }

    
    
    
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
            Object row[] = new Object[7];
            row[0] = i.getDental();
            row[1] = i.getFitness();
            row[2] = i.getVision();
            row[3] = i.getHearing();
            row[4] = i.getTeleHealth();
            dtm.addRow(row);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPolicyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPolicyMax = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrimaryCare = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSpecialistCare = new javax.swing.JTextField();
        txtSurgery = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLabServices = new javax.swing.JTextField();
        txtEmergencyRoomCare = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPolicyType = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        txtAnnualOut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtInpatients = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        LaboratoryList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        HospitalList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PharmacyList = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        PatientList = new javax.swing.JList<>();
        jComboBoxAgeGroup = new javax.swing.JComboBox<>();
        txtDeductible2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboHospital = new javax.swing.JComboBox<>();
        jComboLaboratories = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboPharmacy = new javax.swing.JComboBox<>();
        btnAddHospital = new javax.swing.JButton();
        btnAddLaboratory = new javax.swing.JButton();
        btnAddPharmacy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 117, -1));

        jLabel2.setText("Policy Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Monthly Premium:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, -1, -1));
        add(txtMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 80, -1));

        jLabel7.setText("Policy Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel6.setText("Age Group :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        add(txtPolicyMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 110, -1));

        jLabel15.setText("Policy Maximum:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(83, 103, 142));
        jLabel8.setText("Co-Payment After Deductable:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        add(txtPrimaryCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 50, -1));

        jLabel9.setText("Primary Care:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel10.setText("Specialist Care:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));
        add(txtSpecialistCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 50, -1));
        add(txtSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 50, -1));

        jLabel14.setText("Surgery:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 70, -1));

        jLabel13.setText("Laboratory Services:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));
        add(txtLabServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, -1));
        add(txtEmergencyRoomCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 50, -1));

        jLabel12.setText("Emergency Room Care:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, -1));
        add(txtPolicyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 117, -1));

        saveBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 760, 170, 70));

        UpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdateBtn.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Update");
        UpdateBtn.setBorder(null);
        UpdateBtn.setBorderPainted(false);
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 760, 180, 70));

        jLabel39.setText("Annual Out-of Pocket:");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));
        add(txtAnnualOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 117, -1));

        jLabel18.setText("Annual Deductible :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, -1, -1));
        add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, -1));

        jLabel40.setText("Inpatient Admissions:");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 160, -1));
        add(txtInpatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 50, -1));

        LaboratoryList.setBorder(javax.swing.BorderFactory.createTitledBorder("Laboratories included"));
        LaboratoryList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(LaboratoryList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 180, 140));

        HospitalList.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospitals included"));
        HospitalList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(HospitalList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 160, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dental", "Fitness", "Vision", "Hearing", "TeleHealth"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 800, 110));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(83, 103, 142));
        jLabel5.setText("Plan Features:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 110, -1));

        jLabel21.setText("ZipCode:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        PharmacyList.setBorder(javax.swing.BorderFactory.createTitledBorder("Pharmacy included"));
        PharmacyList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(PharmacyList);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, 140));

        PatientList.setBorder(javax.swing.BorderFactory.createTitledBorder("Patients in this Policy"));
        PatientList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane6.setViewportView(PatientList);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 190, 140));

        jComboBoxAgeGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18-30", "30-45", "45-60", "60-80", "80-100" }));
        add(jComboBoxAgeGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, -1));

        txtDeductible2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtDeductible2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 80, -1));

        jLabel11.setText("Hospitals:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, -1, -1));

        jComboHospital.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jComboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 170, -1));

        jComboLaboratories.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jComboLaboratories, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 170, -1));

        jLabel16.setText("Laboratories:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, -1, -1));

        jLabel17.setText("Pharmacy:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, -1, -1));

        jComboPharmacy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jComboPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, 170, -1));

        btnAddHospital.setBackground(new java.awt.Color(0, 0, 0));
        btnAddHospital.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHospital.setText("Add");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });
        add(btnAddHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 450, -1, -1));

        btnAddLaboratory.setBackground(new java.awt.Color(0, 0, 0));
        btnAddLaboratory.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLaboratory.setText("Add");
        btnAddLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLaboratoryActionPerformed(evt);
            }
        });
        add(btnAddLaboratory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 540, -1, -1));

        btnAddPharmacy.setBackground(new java.awt.Color(0, 0, 0));
        btnAddPharmacy.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPharmacy.setText("Add");
        btnAddPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacyActionPerformed(evt);
            }
        });
        add(btnAddPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 630, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW INSURANCE POLICY");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/double_left_50px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 90));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1100, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 1100, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
            txtPolicyMax.setEnabled(false);
            jComboBoxAgeGroup.setEditable(false);
            txtPolicyName.setEnabled(false);
            txtMonthly.setEnabled(false); 
            txtMin.setEnabled(false);
            txtPrimaryCare.setEnabled(false);
            txtAnnualOut.setEnabled(false);
            txtSpecialistCare.setEnabled(false); 
            txtEmergencyRoomCare.setEnabled(false);
            txtSurgery.setEnabled(false);
            txtLabServices.setEnabled(false);
            txtInpatients.setEnabled(false);
            txtZipCode.setEnabled(false);
            txtMin.setEnabled(false);
            txtPolicyType.setEnabled(false);
            txtDeductible2.setEnabled(false);
            jComboBoxAgeGroup.setEnabled(false);
            btnAddHospital.setEnabled(false);
        btnAddLaboratory.setEnabled(false);
        btnAddPharmacy.setEnabled(false);
            
            
            
            
            
           String age= (String) jComboBoxAgeGroup.getSelectedItem();
        

            i.setAgeGroup(age);
            i.setMonthlyPremium(Double.parseDouble(txtMonthly.getText()));
            i.setOutOfPocket((txtAnnualOut.getText()));         
            i.setPolicyMax(txtPolicyMax.getText());
            i.setPolicyName(txtPolicyName.getText());          
            i.setSpecialist(Integer.parseInt(txtSpecialistCare.getText()));
            i.setPrimaryCare(Integer.parseInt(txtPrimaryCare.getText()));
            i.setPolicyType(txtPolicyType.getText());
            i.setLaboratoryservices(Integer.parseInt(txtLabServices.getText())); 
            i.setZipCode(txtZipCode.getText());
            i.setEmergency(Integer.parseInt(txtEmergencyRoomCare.getText()));
            i.setSurgery(Integer.parseInt(txtSurgery.getText()));
            i.setInPatients(Integer.parseInt(txtInpatients.getText()));
            i.setDeductable(Double.parseDouble( txtDeductible2.getText()));
            
            
        saveBtn.setEnabled(false);
        UpdateBtn.setEnabled(true);
        
        
            JOptionPane.showMessageDialog(null, " Saved Successfully");
        
        
       
    }//GEN-LAST:event_saveBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed

            
             txtPolicyMax.setEnabled(true);
            txtPolicyName.setEnabled(true);
            txtMonthly.setEnabled(true); 
            txtMin.setEnabled(false);
            txtPrimaryCare.setEnabled(true);
            txtAnnualOut.setEnabled(true);
            txtSpecialistCare.setEnabled(true); 
            txtEmergencyRoomCare.setEnabled(true);
            txtSurgery.setEnabled(true);
            txtLabServices.setEnabled(true);
            txtInpatients.setEnabled(true);
            txtZipCode.setEnabled(true);
            txtPolicyType.setEnabled(true);
             txtDeductible2.setEnabled(true);
            jComboBoxAgeGroup.setEnabled(true);
            btnAddHospital.setEnabled(true);
        btnAddLaboratory.setEnabled(true);
        btnAddPharmacy.setEnabled(true);
            
            
            
            saveBtn.setEnabled(true);
            UpdateBtn.setEnabled(false);
            
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed

        
            String x = (String) jComboHospital.getSelectedItem();

            i.addHospitals(x);

            DefaultListModel DLM = new DefaultListModel();

            for (int counter = 0; counter < i.getHospitalList().size(); counter++) {
                DLM.addElement(i.getHospitalList().get(counter));
                
            }
            try{
            HospitalList.setModel(DLM);
            int y = jComboHospital.getSelectedIndex();
            jComboHospital.removeItemAt(y);
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, " All the hospitals are already added");
            
            }

    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void btnAddLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLaboratoryActionPerformed
        
            String x = (String) jComboLaboratories.getSelectedItem();

            i.addLaboratory(x);

            DefaultListModel DLL = new DefaultListModel();

            for(int counter=0;counter<i.getLaboratoryList().size();counter++)
            {DLL.addElement(i.getLaboratoryList().get(counter));
            }
try{
            LaboratoryList.setModel(DLL);
            int y=jComboLaboratories.getSelectedIndex();
            jComboLaboratories.removeItemAt(y);
    }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, " All the laboratories are already added");
            
            }
      
    }//GEN-LAST:event_btnAddLaboratoryActionPerformed

    private void btnAddPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacyActionPerformed
        // TODO add your handling code here:
        
            String x = (String) jComboPharmacy.getSelectedItem();

            i.addPharmacy(x);

            DefaultListModel DLP = new DefaultListModel();

            {for(int counter=0;counter<i.getPharmacyList().size();counter++)
                {DLP.addElement(i.getPharmacyList().get(counter));
                }

                PharmacyList.setModel(DLP);
              
                try{int y=jComboPharmacy.getSelectedIndex();
                System.out.println(y);
                jComboPharmacy.removeItemAt(y);
                }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, " All the pharmacies are already added");
            
            }
            }
        

    }//GEN-LAST:event_btnAddPharmacyActionPerformed

    public void populateHospitals()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getHospitalList().size(); counter++) {
                    DLM.addElement(i.getHospitalList().get(counter));
                }
                HospitalList.setModel(DLM);
    }
    
    public void populateLaboratory()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getLaboratoryList().size(); counter++) {
                    DLM.addElement(i.getLaboratoryList().get(counter));
                }
                LaboratoryList.setModel(DLM);
    }
     public void populatePharmacy()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getPharmacyList().size(); counter++) {
                    DLM.addElement(i.getPharmacyList().get(counter));
                }
                PharmacyList.setModel(DLM);
    }
     
     public void populatePatients()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getUserAccountList().size(); counter++) {
                    DLM.addElement(i.getUserAccountList().get(counter));
                }
                PatientList.setModel(DLM);
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> HospitalList;
    private javax.swing.JList<String> LaboratoryList;
    private javax.swing.JList<String> PatientList;
    private javax.swing.JList<String> PharmacyList;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnAddLaboratory;
    private javax.swing.JButton btnAddPharmacy;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxAgeGroup;
    private javax.swing.JComboBox<String> jComboHospital;
    private javax.swing.JComboBox<String> jComboLaboratories;
    private javax.swing.JComboBox<String> jComboPharmacy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtAnnualOut;
    private javax.swing.JTextField txtDeductible2;
    private javax.swing.JTextField txtEmergencyRoomCare;
    private javax.swing.JTextField txtInpatients;
    private javax.swing.JTextField txtLabServices;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtPolicyMax;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyType;
    private javax.swing.JTextField txtPrimaryCare;
    private javax.swing.JTextField txtSpecialistCare;
    private javax.swing.JTextField txtSurgery;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
