/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientHospitalAppointmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sayu
 */
public class HospitalAppointment extends javax.swing.JPanel {

    /**
     * Creates new form SeeResultJPanel
     */
    EcoSystem ecosystem;
    JPanel userProcessContainer;
    UserAccount account;
    Patient patient;
    Date date;
    InsurancePolicy Insurancepolicy;
    String policy;
    
    public HospitalAppointment(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        String patientName = account.getUsername();
        dateApp.setDate(new Date());
        
        
        for (Patient p : ecosystem.getPatientDirectory().getpatientlist()) {
 
            if (p.getUserName().equals(patientName)) {
                patient = p;               
            }
        }

        Insurancepolicy = patient.getInsurance();
        policy=Insurancepolicy.toString();
        
        tblRequest.getTableHeader().setFont(new Font("SansSerif 14 Plain",Font.BOLD,15));
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        UIManager.put("tblRequest.gridColor", new ColorUIResource(Color.BLACK));
       
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(51,47,73));
         headerRenderer.setForeground(Color.WHITE);

        for (int i = 0; i < tblRequest.getModel().getColumnCount(); i++) {
            tblRequest.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        
        tblRequest.setShowGrid(true);
        tblRequest.getTableHeader().setFont(new Font("SansSerif 14 Plain",Font.BOLD,16));
        
        String from = "08:00:00", to = "20:00:00";
        LocalTime fromTime = LocalTime.parse(from), toTime = LocalTime.parse(to);

        for (LocalTime counter = fromTime;
                counter.compareTo(toTime) <= 0;
                counter = counter.plusMinutes(30)) {
            jComboBoxTime.addItem(counter.toString());

                    }
        populateComboBox();
    }
    
   public void populateComboBox()
   {for (InsurancePolicy a: ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList())
   {    
   
       if(a.getPolicyName().equalsIgnoreCase(policy))
       {for (int counter = 0; counter < a.getHospitalList().size(); counter++) {
           
                    jComboBoxHospitalList.addItem(a.getHospitalList().get(counter));
                }
       
               }
   }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxPrimaryHospital = new javax.swing.JCheckBox();
        jComboBoxTime = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jComboBoxHospitalList = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequest.setBackground(new java.awt.Color(242, 242, 242));
        tblRequest.setForeground(new java.awt.Color(255, 255, 255));
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AppointmentNo.", "Hospital", "Date", "Time", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequest.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblRequest);
        if (tblRequest.getColumnModel().getColumnCount() > 0) {
            tblRequest.getColumnModel().getColumn(0).setResizable(false);
            tblRequest.getColumnModel().getColumn(1).setResizable(false);
            tblRequest.getColumnModel().getColumn(2).setResizable(false);
            tblRequest.getColumnModel().getColumn(3).setResizable(false);
            tblRequest.getColumnModel().getColumn(4).setResizable(false);
            tblRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 500, 855, 137));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("BOOK AN APPOINTMENT ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 19, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/back_to_50px.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 19, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Appointment Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 450, -1, -1));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxPrimaryHospital.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jCheckBoxPrimaryHospital.setText("Primary Hospital");
        jPanel1.add(jCheckBoxPrimaryHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 9, -1, -1));

        jComboBoxTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBoxTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 109, 73, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Choose hospital:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 9, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("If other hospital please choose from the list:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 49, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Choose appointment Date and Time:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 106, -1, -1));
        jPanel1.add(txtDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 158, 191, -1));

        jComboBoxHospitalList.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBoxHospitalList, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 53, 183, -1));

        btnSubmit.setBackground(new java.awt.Color(242, 242, 242));
        btnSubmit.setText("Confirm");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 225, 266, 62));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Appointment Details:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 156, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 74, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtDetails.getText().equals(""))
        { JOptionPane.showMessageDialog(null, "Please fill the appointment details", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
       date=dateApp.getDate();
       LocalDate dates=new java.sql.Date(date.getTime()).toLocalDate();
       String selected=(String) jComboBoxTime.getSelectedItem();
      
       String hospital;
        boolean primary= jCheckBoxPrimaryHospital.isSelected();
        if(primary==true)
        { hospital= patient.getPrimaryHospital();      
        }else{
          hospital= (String) jComboBoxHospitalList.getSelectedItem();
        }
        
        PatientHospitalAppointmentWorkRequest r = new PatientHospitalAppointmentWorkRequest();
        r.setHospital(hospital);
        r.setMessage(txtDetails.getText());
        r.setSender(account);
        r.setAppDate(dates);
        r.setTime(selected);
        r.setStatus("Appointment requested");
        r.setInsurance(Insurancepolicy);
        r.setDoctor("not assigned");
        r.setDoctor("not available");
        Map<String,Date> reqMap = r.getStatusMap();
        reqMap.put("New Appointment Request: "+hospital, new Date());
        r.setStatusMap(reqMap); 
        r.setRequestDate(new Date());
        ecosystem.getHospitalQueue().hospitalRequestList().add(r);
        account.getHospitalWorkQueue().hospitalRequestList().add(r);
        
        String s;
        DefaultTableModel model = (DefaultTableModel)tblRequest.getModel();
        model.setRowCount(0);

            Object[] row = new Object[7];
            row[0] = r;
            row[1] = r.getHospital();
            row[2] = r.getAppDate();
            row[3] = r.getTime();
            row[4] = r.getMessage();
            row[5] = r.getStatus();
            model.addRow(row);
             JOptionPane.showMessageDialog(null,"Successfully requested appointment");
             
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void dateAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateAppMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==2)
        {    
        }   
    }//GEN-LAST:event_dateAppMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox jCheckBoxPrimaryHospital;
    private javax.swing.JComboBox<String> jComboBoxHospitalList;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtDetails;
    // End of variables declaration//GEN-END:variables
}
