/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineScientistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.VaccineEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.VaccineWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manasa
 */
public class CreateVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVaccineJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;  
    private Enterprise enterprise;
    private Organization organization;
    public CreateVaccineJPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise,Organization organization,EcoSystem business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        this.setSize(1466, 902);
        introPanel.setBounds(171, 33, 1293, 101);
        jLabel4.setBounds(1, 1, 160, 113);
        btnCreate.setBounds(1207, 135, 258, 73);
        jPanel4.setBounds(2, 150, 1049, 384);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        introPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblCore = new javax.swing.JLabel();
        txtCore = new javax.swing.JTextField();
        txtAllergens = new javax.swing.JTextField();
        lblAllergens = new javax.swing.JLabel();
        btnIntra = new javax.swing.JRadioButton();
        lblAdministration = new javax.swing.JLabel();
        btnPills = new javax.swing.JRadioButton();
        quantityMaxAgeSpinner = new javax.swing.JSpinner();
        quantityMinAgeSpinner = new javax.swing.JSpinner();
        lblMin = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHeart = new javax.swing.JRadioButton();
        lblCond = new javax.swing.JLabel();
        btnDiabetes = new javax.swing.JRadioButton();
        btnCovid = new javax.swing.JRadioButton();
        btnResp = new javax.swing.JRadioButton();
        btnNight = new javax.swing.JRadioButton();
        btnAfternoon = new javax.swing.JRadioButton();
        btnMorning = new javax.swing.JRadioButton();
        lblDosage = new javax.swing.JLabel();
        mornDosage = new javax.swing.JSpinner();
        afterDosage = new javax.swing.JSpinner();
        nightDosage = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtOther = new javax.swing.JTextField();
        lblOther = new javax.swing.JLabel();
        txtPreservations = new javax.swing.JTextField();
        txtSide = new javax.swing.JTextField();
        lblPreservation = new javax.swing.JLabel();
        lblSide = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        btnCreate.setBackground(new java.awt.Color(0, 0, 51));
        btnCreate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/test_tube_25px.png"))); // NOI18N
        btnCreate.setText("CREATE VACCINE");
        btnCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCreate.setContentAreaFilled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        introPanel.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drug Discovery Portal");

        lblEnterprise.setBackground(new java.awt.Color(51, 51, 51));
        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterprise.setText("Enterprise:");
        lblEnterprise.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblAccount.setBackground(new java.awt.Color(51, 51, 51));
        lblAccount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("Enterprise:");
        lblAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        backJButton.setBackground(new java.awt.Color(0, 0, 102));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home2.png"))); // NOI18N
        backJButton.setText("Home");
        backJButton.setBorder(null);
        backJButton.setBorderPainted(false);
        backJButton.setContentAreaFilled(false);
        backJButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introPanelLayout = new javax.swing.GroupLayout(introPanel);
        introPanel.setLayout(introPanelLayout);
        introPanelLayout.setHorizontalGroup(
            introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPanelLayout.createSequentialGroup()
                .addGroup(introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(introPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(introPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89)))
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        introPanelLayout.setVerticalGroup(
            introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(introPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("New Drug Details");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 51));
        lblName.setText("Name:");

        lblDesc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(0, 0, 51));
        lblDesc.setText("Description:");

        txtDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        lblCore.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCore.setForeground(new java.awt.Color(0, 0, 51));
        lblCore.setText("Core Component:");

        txtCore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        txtAllergens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        txtAllergens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergensActionPerformed(evt);
            }
        });

        lblAllergens.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAllergens.setForeground(new java.awt.Color(0, 0, 51));
        lblAllergens.setText("Any Allergens:");

        btnIntra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIntra.setForeground(new java.awt.Color(0, 0, 51));
        btnIntra.setText("Intravenous");
        btnIntra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnIntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntraActionPerformed(evt);
            }
        });

        lblAdministration.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAdministration.setForeground(new java.awt.Color(0, 0, 51));
        lblAdministration.setText("Administration:");

        btnPills.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnPills.setForeground(new java.awt.Color(0, 0, 51));
        btnPills.setText("Pills");
        btnPills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnPills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPillsActionPerformed(evt);
            }
        });

        quantityMaxAgeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantityMaxAgeSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        quantityMinAgeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantityMinAgeSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblMin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMin.setForeground(new java.awt.Color(0, 0, 51));
        lblMin.setText("Min :");

        lblMax.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMax.setForeground(new java.awt.Color(0, 0, 51));
        lblMax.setText("Max:");

        lblAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 0, 51));
        lblAge.setText("Age-Group:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("(in years)");

        btnHeart.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHeart.setForeground(new java.awt.Color(0, 0, 51));
        btnHeart.setText("Heart Disease");
        btnHeart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeartActionPerformed(evt);
            }
        });

        lblCond.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCond.setForeground(new java.awt.Color(0, 0, 51));
        lblCond.setText("Usage For Condition:");

        btnDiabetes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDiabetes.setForeground(new java.awt.Color(0, 0, 51));
        btnDiabetes.setText("Diabetes");
        btnDiabetes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiabetesActionPerformed(evt);
            }
        });

        btnCovid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCovid.setForeground(new java.awt.Color(0, 0, 51));
        btnCovid.setText("Covid");
        btnCovid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCovidActionPerformed(evt);
            }
        });

        btnResp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnResp.setForeground(new java.awt.Color(0, 0, 51));
        btnResp.setText("Respiratory problems");
        btnResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespActionPerformed(evt);
            }
        });

        btnNight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNight.setForeground(new java.awt.Color(0, 0, 51));
        btnNight.setText("Night");
        btnNight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        btnNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNightActionPerformed(evt);
            }
        });

        btnAfternoon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAfternoon.setForeground(new java.awt.Color(0, 0, 51));
        btnAfternoon.setText("Afternoon");
        btnAfternoon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        btnMorning.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMorning.setForeground(new java.awt.Color(0, 0, 51));
        btnMorning.setText("Morning");
        btnMorning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        btnMorning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorningActionPerformed(evt);
            }
        });

        lblDosage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDosage.setForeground(new java.awt.Color(0, 0, 51));
        lblDosage.setText("Dosage:");

        mornDosage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        mornDosage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        afterDosage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        afterDosage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        nightDosage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        nightDosage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("(milligrams)");

        txtOther.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblOther.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblOther.setForeground(new java.awt.Color(0, 0, 51));
        lblOther.setText("Other Instructions:");

        txtPreservations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        txtSide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblPreservation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPreservation.setForeground(new java.awt.Color(0, 0, 51));
        lblPreservation.setText("Preservation instructions:");

        lblSide.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSide.setForeground(new java.awt.Color(0, 0, 51));
        lblSide.setText("Possible Side Effects:");

        jLabel5.setFont(new java.awt.Font("Sukhumvit Set", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Drug Details");

        jLabel6.setFont(new java.awt.Font("Sukhumvit Set", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Drug Usage");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Precautions");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPreservation)
                    .addComponent(lblSide))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPreservations, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblOther)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDesc)
                        .addComponent(lblName))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCore))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAllergens)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAllergens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(222, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lblMax)
                                    .addGap(13, 13, 13))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel13))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(lblAge)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMin)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(lblCond)
                                            .addGap(51, 51, 51)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(quantityMinAgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(quantityMaxAgeSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDiabetes, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnPills, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblAdministration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIntra, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(lblDosage)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel21)
                                    .addGap(3, 3, 3)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(btnMorning, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mornDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(btnAfternoon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(afterDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(btnNight, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nightDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7)))
                .addContainerGap(995, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblCore)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtCore)
                            .addGap(1, 1, 1)))
                    .addComponent(lblName))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAllergens, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAllergens))
                                .addGap(5, 5, 5))
                            .addComponent(lblDesc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAdministration)
                                    .addComponent(btnIntra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPills, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantityMaxAgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMax)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quantityMinAgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMin)
                                    .addComponent(lblAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCond)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblDosage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mornDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMorning, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAfternoon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(afterDosage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nightDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnDiabetes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreservations, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreservation)
                            .addComponent(lblOther))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSide)))
                    .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/drugDiscovery.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(introPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(508, 508, 508)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(introPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
            userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineScientistWorkAreaJPanel sysAdminwjp = (VaccineScientistWorkAreaJPanel) component;

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        lblName.setForeground(Color.black);
        lblDesc.setForeground(Color.black);
        lblCond.setForeground(Color.black);
        lblPreservation.setForeground(Color.black);
        lblOther.setForeground(Color.black);
        lblCore.setForeground(Color.black);
        lblAllergens.setForeground(Color.black);
        lblDosage.setForeground(Color.black);
        lblAdministration.setForeground(Color.black);
        lblAge.setForeground(Color.black);
        lblSide.setForeground(Color.black);
        lblMax.setForeground(Color.black);
        lblMin.setForeground(Color.black);

        String error = "";
        if((txtName.getText().equalsIgnoreCase("")) ||
            (txtDesc.getText().equalsIgnoreCase(""))||
            (txtCore.getText().equals(""))||
            (txtAllergens.getText().equalsIgnoreCase(""))||
            (txtOther.getText().equalsIgnoreCase(""))||
            (txtSide.getText().equalsIgnoreCase(""))||
            (txtPreservations.getText().equalsIgnoreCase(""))||
            ((!btnResp.isSelected()) &&(!btnCovid.isSelected()) && (!btnHeart.isSelected()) &&(!btnDiabetes.isSelected()))||
            ((!btnPills.isSelected()) &&(!btnIntra.isSelected())) ||
            ((!btnMorning.isSelected()) &&(!btnAfternoon.isSelected()) && (!btnNight.isSelected()))
        ){
            error="\nAll the fields are Mandatory!!!";
            //Highligting the unfilled blocks to RED
            if((txtName.getText().equalsIgnoreCase(""))){
                lblName.setForeground(Color.red);
            }
            if((txtPreservations.getText().equalsIgnoreCase(""))){
                lblPreservation.setForeground(Color.red);
            }
            if((txtSide.getText().equalsIgnoreCase(""))){
                lblSide.setForeground(Color.red);
            }
            if((txtOther.getText().equalsIgnoreCase(""))){
                lblOther.setForeground(Color.red);
            }
            if((txtDesc.getText().equalsIgnoreCase(""))){
                lblDesc.setForeground(Color.red);
            }
            if((txtCore.getText().equalsIgnoreCase(""))){
                lblCore.setForeground(Color.red);
            }
            if((txtAllergens.getText().equalsIgnoreCase(""))){
                lblAllergens.setForeground(Color.red);
            }
            if((!btnResp.isSelected()) &&(!btnCovid.isSelected()) && (!btnHeart.isSelected()) &&(!btnDiabetes.isSelected())){
                lblCond.setForeground(Color.red);
            }
            if((!btnPills.isSelected()) &&(!btnIntra.isSelected())){
                lblAdministration.setForeground(Color.red);
            }
            if((!btnMorning.isSelected()) &&(!btnAfternoon.isSelected()) && (!btnNight.isSelected())){
                lblDosage.setForeground(Color.red);
            }
            if(((Integer)quantityMinAgeSpinner.getValue() <= 0) || ((Integer)quantityMaxAgeSpinner.getValue()<=0)){
                lblAge.setForeground(Color.red);
            }

        }
        if(!error.equals("")){
            JOptionPane.showMessageDialog(null,error);
            return;
        }else{
            int minAge = (Integer)quantityMinAgeSpinner.getValue();
            int maxAge = (Integer)quantityMaxAgeSpinner.getValue();
            if((minAge <= 0) || (maxAge<=0)){
                if(minAge <= 0){
                    lblMin.setForeground(Color.red);
                }else{
                    lblMax.setForeground(Color.red);
                }
                JOptionPane.showMessageDialog(null, "Minimum or Maximum Age For Vaccine usage cannot be zero!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if((minAge > 100) || (minAge < 1) ||(maxAge > 100) || (maxAge < 1)){
                JOptionPane.showMessageDialog(null, "Vaccine age group needs to be of range 1 to 100 years only!", "Warning", JOptionPane.WARNING_MESSAGE);
                lblMin.setForeground(Color.red);
                lblMax.setForeground(Color.red);
                return;
            }
            if((minAge>maxAge)){
                JOptionPane.showMessageDialog(null, "Minimum age cannot be more than maximum age!", "Warning", JOptionPane.WARNING_MESSAGE);
                lblMin.setForeground(Color.red);
                lblMax.setForeground(Color.red);
                return;
            }
            if(btnMorning.isSelected()) {
                int mornDose = (Integer)mornDosage.getValue();
                if((mornDose <= 0)){

                    JOptionPane.showMessageDialog(null, "Morning Dosage Selected!\nDosage for selected time cannot be zero!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            if(btnAfternoon.isSelected()){
                int aftDose = (Integer)afterDosage.getValue();
                if((aftDose <= 0)){

                    JOptionPane.showMessageDialog(null, "Afternoon Dosage Selected!\nDosage for selected time cannot be zero!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            if(btnNight.isSelected()){
                int nightDose = (Integer)nightDosage.getValue();
                if((nightDose <= 0)){

                    JOptionPane.showMessageDialog(null, "Night Dosage Selected!\nDosage for selected time cannot be zero!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

        }
        if(!error.equals("")){
            JOptionPane.showMessageDialog(null,error);
        }else{
            VaccineEnterprise enterPrise = (VaccineEnterprise)enterprise;
            Vaccine vaccine = new Vaccine();
            vaccine.setName(txtName.getText());
            vaccine.setDescription(txtDesc.getText());
            vaccine.setCoreComponents(txtCore.getText());
            vaccine.setAllergens(txtAllergens.getText());
            vaccine.setMinAgeGroup((Integer)quantityMinAgeSpinner.getValue());
            vaccine.setMaxAgeGroup((Integer)quantityMaxAgeSpinner.getValue());
            if(btnPills.isSelected()){
                vaccine.setAdministration(btnPills.getName());
            }else{
                vaccine.setAdministration(btnIntra.getName());
            }
            String condition = "";
            if(btnHeart.isSelected()){
                condition=btnHeart.getName();
            }else if(btnCovid.isSelected()){
                condition=btnCovid.getName();
            }else if(btnResp.isSelected()){
                condition=btnResp.getName();
            }else{
                condition=btnDiabetes.getName();
            }
            vaccine.setCondition(condition);
            int dose =0;
            Map<String,Integer> doseMap = vaccine.getDosage();
            if((Integer)mornDosage.getValue()<=0){
                doseMap.put("Morning", dose);
            }else{
                doseMap.put("Morning", (Integer)mornDosage.getValue());
            }
            if((Integer)afterDosage.getValue()<=0){
                doseMap.put("Afternoon", dose);
            }else{
                doseMap.put("Afternoon", (Integer)afterDosage.getValue());
            }
            if((Integer)nightDosage.getValue()<=0){
                doseMap.put("Night", dose);
            }else{
                doseMap.put("Night", (Integer)nightDosage.getValue());
            }
            vaccine.setDosage(doseMap);
            vaccine.setPreservations(txtPreservations.getText());
            vaccine.setSideeffects(txtSide.getText());
            vaccine.setOther(txtOther.getText());
            vaccine.setUpdateDate();
            vaccine.setUsername(account);
            vaccine.setEnterpriseName(enterprise.getName());
            vaccine.setEnterprise(enterprise);

            enterPrise.getVaccineDirectory().addVaccine(vaccine);

            VaccineWorkRequest vaccineReq = new VaccineWorkRequest();
            vaccineReq.setEnterprise(enterprise.getName());
            vaccineReq.setSender(account);
            vaccineReq.setVaccine(vaccine);
            vaccineReq.setRequestDate(new Date());
            vaccineReq.setSuccess("ongoing");
            vaccineReq.setPhase("development");
            Map<String,Date> statusMap = vaccineReq.getStatusMap();
            statusMap.put("Formulation Phase", new Date());
            vaccineReq.setStatusMap(statusMap);
            account.getVaccineWorkQueue().addWorkRequest(vaccineReq);
            business.getVaccineQueue().addWorkRequest(vaccineReq);

            JOptionPane.showMessageDialog(null,"Vaccine Added Successfully!!!");
            txtName.setText("");
            txtDesc.setText("");
            txtCore.setText("");
            txtAllergens.setText("");
            txtPreservations.setText("");
            txtOther.setText("");
            txtSide.setText("");
            btnDiabetes.setSelected(false);
            btnCovid.setSelected(false);
            btnHeart.setSelected(false);
            btnResp.setSelected(false);
            quantityMinAgeSpinner.setValue(0);
            quantityMaxAgeSpinner.setValue(0);
            mornDosage.setValue(0);
            afterDosage.setValue(0);
            nightDosage.setValue(0);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtAllergensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergensActionPerformed

    private void btnIntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntraActionPerformed
        // TODO add your handling code here:
        btnIntra.setName("Intravenous");
        btnPills.setSelected(false);
    }//GEN-LAST:event_btnIntraActionPerformed

    private void btnPillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPillsActionPerformed
        // TODO add your handling code here:
        btnPills.setName("Pills");
        btnIntra.setSelected(false);
    }//GEN-LAST:event_btnPillsActionPerformed

    private void btnHeartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeartActionPerformed
        // TODO add your handling code here:
        btnHeart.setName("Heart");
        btnDiabetes.setSelected(false);
        btnCovid.setSelected(false);
        btnResp.setSelected(false);
    }//GEN-LAST:event_btnHeartActionPerformed

    private void btnDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiabetesActionPerformed
        // TODO add your handling code here:
        btnDiabetes.setName("Diabetes");
        btnHeart.setSelected(false);
        btnCovid.setSelected(false);
        btnResp.setSelected(false);
    }//GEN-LAST:event_btnDiabetesActionPerformed

    private void btnCovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCovidActionPerformed
        // TODO add your handling code here:
        btnCovid.setName("Covid");
        btnDiabetes.setSelected(false);
        btnHeart.setSelected(false);
        btnResp.setSelected(false);
    }//GEN-LAST:event_btnCovidActionPerformed

    private void btnRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespActionPerformed
        // TODO add your handling code here:
        btnResp.setName("Resp");
        btnDiabetes.setSelected(false);
        btnCovid.setSelected(false);
        btnHeart.setSelected(false);
    }//GEN-LAST:event_btnRespActionPerformed

    private void btnNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNightActionPerformed

    private void btnMorningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMorningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner afterDosage;
    private javax.swing.JButton backJButton;
    private javax.swing.JRadioButton btnAfternoon;
    private javax.swing.JRadioButton btnCovid;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnDiabetes;
    private javax.swing.JRadioButton btnHeart;
    private javax.swing.JRadioButton btnIntra;
    private javax.swing.JRadioButton btnMorning;
    private javax.swing.JRadioButton btnNight;
    private javax.swing.JRadioButton btnPills;
    private javax.swing.JRadioButton btnResp;
    private javax.swing.JPanel introPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAdministration;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergens;
    private javax.swing.JLabel lblCond;
    private javax.swing.JLabel lblCore;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDosage;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblPreservation;
    private javax.swing.JLabel lblSide;
    private javax.swing.JSpinner mornDosage;
    private javax.swing.JSpinner nightDosage;
    private javax.swing.JSpinner quantityMaxAgeSpinner;
    private javax.swing.JSpinner quantityMinAgeSpinner;
    private javax.swing.JTextField txtAllergens;
    private javax.swing.JTextField txtCore;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtPreservations;
    private javax.swing.JTextField txtSide;
    // End of variables declaration//GEN-END:variables
}
